MRBookingDemo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("webapp.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

webapp/urls.py
from django.urls import path
from django.contrib import admin
from webapp import views

urlpatterns = [
    path("admin/", admin.site.urls,name="admin"),
    path("", views.login, name="login"),
    path("login/", views.login, name="login"),
    path("index/", views.index, name="index"),
    path("book/", views.book,name="book"),
    path("mybooking/", views.mybooking, name="mybooking"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout,name="logout"),
]

webapp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    User Table
    """
    phone = models.CharField(max_length=32, default='80008000')
    sex_choice = (
        (1, 'M'),
        (2, 'F')
    )
    sex = models.IntegerField(choices=sex_choice,default=1)
    email = models.EmailField(max_length=32)


class MeetingRoom(models.Model):
    """
    Meeting Room Table
    """
    caption = models.CharField(max_length=32)
    num = models.IntegerField()

    def __str__(self):
        return self.caption


class RoomBooking(models.Model):
    """
    Room Booking Table
    """
    user = models.ForeignKey(to='UserInfo', on_delete=models.CASCADE)
    room = models.ForeignKey(to='MeetingRoom', on_delete=models.CASCADE)
    date = models.DateField()
    time_choices = (
        (1, '8:00'),
        (2, '9:00'),
        (3, '10:00'),
        (4, '11:00'),
        (5, '12:00'),
        (6, '13:00'),
        (7, '14:00'),
        (8, '15:00'),
        (9, '16:00'),
        (10, '17:00'),
        (11, '18:00'),
        (12, '19:00'),
        (13, '20:00'),
    )
    time_id = models.IntegerField(choices=time_choices)

    class Meta:
        """
        Combination
        """
        unique_together = (
            ('room','date','time_id'),
        )

    def __str__(self):
        return str(self.user)+"has booked the "+str(self.room)+" successfully"

webapp/forms.py
from django import forms
from django.forms import widgets
from django.forms import ValidationError
from webapp import models
import re


def mobile_validate(value):
    mobile_re = re.compile(r'\d{8}/g')
    if not mobile_re.match(value):
        raise ValidationError('Please enter valid contact no')


class RegForm(forms.Form):
    username = forms.CharField(
        label='UserName',
        max_length=16,
        widget=widgets.TextInput(attrs={'class':'form-control'}),
        error_messages={
            'required': 'UserName is required',
        }
    )
    password = forms.CharField(
        label='Password',
        min_length=3,
        widget=widgets.PasswordInput(attrs={'class': 'form-control'}),
        error_messages={
            'required':'Password is required',
            'invalid': 'Password is invalida',
            'min_length': 'The minimum length of password must be greater than 3 characters'
        }
    )
    r_password = forms.CharField(
        label='Confirm Password',
        min_length=3,
        widget=widgets.PasswordInput(attrs={'class': 'form-control'}),
        error_messages={
            'required':'Password is required',
            'invalid': 'Password is invalida',
            'min_length': 'The minimum length of password must be greater than 3 characters'
        }
    )

    def clean(self):
        password = self.cleaned_data.get('password')
        rel_password = self.cleaned_data.get("r_password")
        if rel_password and password != rel_password:
            self.add_error("r_password", ValidationError('The confirmed password is not matched'))
        else:
            return self.cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        rep = models.UserInfo.objects.filter(username=username)
        if rep:
            self.add_error("username", ValidationError('The user already exists'))
        else:
            return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        rep = models.UserInfo.objects.filter(email=email)
        if rep:
            self.add_error("email", ValidationError('Email address already exists'))
        else:
            return email

webapp/views.py
import json
import datetime
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import HttpResponse
from django.contrib import auth
from webapp.models import RoomBooking,MeetingRoom,UserInfo
from webapp.forms import RegForm

def register(request):
    form_obj = RegForm()
    if request.method == 'POST':
        form_obj = RegForm(request.POST)
        if form_obj.is_valid():
            form_obj.cleaned_data.pop("r_password")
            UserInfo.objects.create_user(**form_obj.cleaned_data)
            return redirect('/login/')
    return render(request, 'register.html', locals())


def login(request):
    error = ''
    if request.method == "POST":
        username = request.POST.get("username")
        pwd = request.POST.get("password")
        user = auth.authenticate(username=username, password=pwd)
        if user:
            auth.login(request, user)
            request.session['user'] = username
            return redirect("/index/")
        else:
            error = 'The username or password is not correct.'
    return render(request, "login.html",locals())


def index(request):
    # Validate the user session
    user = request.session.get('user')
    if not user:
        return redirect('/login/')

    date = datetime.datetime.now().date()

    book_date = request.GET.get("book_date", date)
    time_choices = RoomBooking.time_choices
    room_list = MeetingRoom.objects.all()

    book_list = RoomBooking.objects.filter(date=book_date)

    htmls = ""
    for room in room_list:
        htmls += "<tr><td>{}({})</td>".format(room.caption, room.num)
        for time_choice in time_choices:
            book = None
            flag = False
            for book in book_list:
                if book.room.pk == room.pk and book.time_id == time_choice[0]:
                    flag = True
                    break
            if flag:
                if request.user.pk == book.user.pk:
                     htmls += "<td class='active item'  room_id={} time_id={}>{}</td>".format(room.pk, time_choice[0], 'Booked')
                else:
                     htmls += "<td class='another_active item'  room_id={} time_id={}>{}</td>".format(room.pk, time_choice[0], book.user.username)
            else:
                 htmls += "<td room_id={} time_id={} class='item'></td>".format(room.pk, time_choice[0])
        htmls += "</tr>"
    return render(request, "index.html", locals())


def book(request):
    post_data = json.loads(request.POST.get("post_data"))   # {"ADD":{"1":["5"],"2":["5","6"]},"DEL":{"3":["9","10"]}}
    choose_date = request.POST.get("choose_date")
    res = {"state": True, "msg": None}
    try:
        # Add booking
        book_list = []
        for room_id, time_id_list in post_data["ADD"].items():
            for time_id in time_id_list:
                book_obj = RoomBooking(user=request.user, room_id=room_id, time_id=time_id, date=choose_date)
                book_list.append(book_obj)
        RoomBooking.objects.bulk_create(book_list)
        # Delete booking
        for room_id, time_id_list in post_data["DEL"].items():
            for time_id in time_id_list:
                RoomBooking.objects.filter(user=request.user, room_id=room_id, time_id=time_id, date=choose_date).delete()
    except Exception as e:
        res["state"] = False
        res["msg"] = str(e)

    return HttpResponse(json.dumps(res))


def logout(request):
    request.session.clear()
    return redirect('/login/')


def mybooking(request):
    book_list = RoomBooking.objects.filter(user=request.user)
    return render(request, 'mybooking.html', locals())

webapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meeting Room Booking - Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/site.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'datetimepicker/bootstrap-datetimepicker.min.css' %}">
    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'datetimepicker/bootstrap-datetimepicker.min.js' %}"></script>
</head>
<body>
{% include 'nav.html' %}
<div class="calender pull-right">
      <div class='input-group' style="width: 380px;left:30px;">
        <span class="font-weight-bold" style="margin-right: 10px;">Choose Booking Date:</span>
            <input type='text' class="form-control" id='datetimepicker1' placeholder=""/>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
      </div>
</div>
<table class="table table-bordered table-striped">
    <thead>
       <tr>
             <th>Meeting Room/Time</th>
              {% for time_choice in time_choices %}
              <th>{{ time_choice.1 }}</th>
              {% endfor %}
       </tr>
    </thead>
<tbody>
     {{ htmls|safe }}
</tbody>
</table>
{% csrf_token %}
<button class="btn btn-success" id="btnBook">Save</button>

<script type="text/javascript">
    Date.prototype.yuan = function (fmt) {
            var o = {
                "M+": this.getMonth() + 1, 
                "d+": this.getDate(), 
                "h+": this.getHours(), 
                "m+": this.getMinutes(), 
                "s+": this.getSeconds(), 
                "q+": Math.floor((this.getMonth() + 3) / 3), 
                "S": this.getMilliseconds()
            };
            if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
            for (var k in o)
                if (new RegExp("(" + k + ")").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
            return fmt;
        };

    var POST_DATA={
        "ADD":{},
        "DEL":{}       
    };

    // Add binding event for td tag
    function BindTd() {
        $(".item").click(function () {

             var room_id=$(this).attr("room_id");
             var time_id=$(this).attr("time_id");

             // cancel booking
             if($(this).hasClass("active")){
                $(this).removeClass("active").empty();

                 if(POST_DATA.DEL[room_id]){
                      POST_DATA.DEL[room_id].push(time_id)
                  }else {
                      POST_DATA.DEL[room_id]=[time_id,]
                  }
             }
             // temporarily cancel
             else if ($(this).hasClass("td_active")){
                 $(this).removeClass("td_active");
                 POST_DATA.ADD[room_id].pop()
             }
             else{ // add booking
                  $(this).addClass("td_active");
                  if(POST_DATA.ADD[room_id]){
                      POST_DATA.ADD[room_id].push(time_id)
                  }else {
                      POST_DATA.ADD[room_id]=[time_id]
                  }


             }
        })
    }
    BindTd();

     if (location.search.slice(11)){
           CHOOSE_DATE = location.search.slice(11)
          }
      else {
           CHOOSE_DATE = new Date().yuan('yyyy-MM-dd');
           }

    $("#btnBook").click(function () {
        $.ajax({
            url:"/book/",
            type:"POST",
            data:{
                 choose_date:CHOOSE_DATE,
                 post_data:JSON.stringify(POST_DATA),
                 csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            dataType:"json",
            success:function (data) {
                console.log(data)
                if(data.state){
                    // booking succeeded
                    location.href=""
                }else {
                    alert("The meeting room is not available.")
                    location.href=""
                }
        }
        })
    });

    $('#datetimepicker1').datetimepicker({
                minView: "month",
                format: 'yyyy-mm-dd',
                startDate: new Date(),
                //bootcssVer: 3,
                autoclose: true,
            }).on('changeDate', book_query);

     function book_query(e) {
         CHOOSE_DATE=e.date.yuan("yyyy-MM-dd");
         location.href="/index/?book_date="+CHOOSE_DATE;
     }
</script>
</body>
</html>

webapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meeting Room Booking - Sign in</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
</head>
<body>
<div class="container">
    <div class="div-center">
      <div class="content">
        <h3>Login</h3>
        <hr />
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="font-weight-bold">Username</label>
                <input type="text" class="form-control" name="username" id="username" placeholder="Username">
            </div>
            <div class="form-group">
                <label for="password" class="font-weight-bold">Password</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password">
            </div>
          <input type="submit" class="btn btn-primary" value="Sign in" />
          <hr />   
        </form>
        <a href="/register/" class="btn btn-link font-weight-bold">Signup</a>
        <p><span>{{ error }}</span></p>
      </div>
      </span>
</div>
</body>
</html>

webapp/templates/mybooking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meeting Room Booking - My booking</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/site.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
</head>
<body>
{% include 'nav.html' %}
<table class="table table-bordered">
    <thead>
   <tr>
        <th>Date</th>
        <th>Room</th>
        <th>Timing</th>
    </tr>
    </thead>
    <tbody>
        {% for book in book_list %}
            <tr>
            <td>{{ book.date }}</td>
            <td>{{ book.room }}</td>
            <td>{{ book.get_time_id_display }}
            </tr>
        {% endfor %}
    </tbody>
</table>
</body>
</html>

webapp/templates/nav.html
<nav class="navbar navbar-inverse navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-header" style="color: white;font-family: Verdana, Arial, sans-serif; font-size: 1.0em; font-weight: bold;">
      Meeting Room Booking ({{ request.user }})
    </div>
    <ul id="navlist">
      <li><a href="/index/">Home</a></li>
      <li><a href="/mybooking/">My booking</a></li>
      <li><a href="/logout/">Logout</a></li>
    </ul>
  </div>
</nav>

webapp/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meeting Room Booking - Sign up</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
</head>
<body>
    <div class="container">
          <div class="content">
            <h3>Signup</h3>
            <form method="post" action="" class="form-horizontal" autocomplete="off" style="margin-top: 70px" novalidate
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group ">
                    <label for="{{ form_obj.username.id_for_label }}"
                           class="col-sm-2 font-weight-bold">{{ form_obj.username.label }}</label>
                    <div class="col-sm-10">
                        {{ form_obj.username }}
                        <span id="helpBlock2" class="help-block">{{ form_obj.username.errors.0 }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}"
                           class="col-sm-2 font-weight-bold">{{ form_obj.password.label }}</label>
                    <div class="col-sm-10">
                        {{ form_obj.password }}
                        <span id="helpBlock2" class="help-block">{{ form_obj.password.errors.0 }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.r_password.id_for_label }}"
                           class="col-sm-2 font-weight-bold">{{ form_obj.r_password.label }}</label>
                    <div class="col-sm-10">
                        {{ form_obj.r_password }}
                        <span id="helpBlock2" class="help-block">{{ form_obj.r_password.errors.0 }}</span>
                    </div>
                </div>
                <input type="submit" class="btn btn-primary" value="Create Account" />
                <hr />
            </form>
            <a href="/login/" class="btn btn-link font-weight-bold">Signin</a>
    </div>
    </body>
</html>